import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Toaster } from "react-hot-toast";
import { AuthProvider } from "@/context/AuthContext";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Amapola Store",
  description: "Generated by Camila Ladner",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col justify-between h-screen`}
      >
        <Toaster
          position="top-right"
          toastOptions={{
            style: {
              background: "#fff8e7", // amarillo suave
              color: "#3a2c1a",       // marrón suave
              fontFamily: "var(--font-manrope)",
              borderRadius: "1rem",
              padding: "12px 16px",
              border: "1px solid #facc15", // amarillo dorado
              boxShadow: "0 4px 12px rgba(234, 179, 8, 0.3)", // dorado suave
            },
            success: {
              iconTheme: {
                primary: "#facc15",
                secondary: "#fff",
              },
            },
            error: {
              iconTheme: {
                primary: "#f43f5e",
                secondary: "#fff",
              },
            },
          }}
        />
        <AuthProvider>
        <Navbar />
        {children}
        <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}


